
[[tm]]

  # ip地址
  ip = "106.3.133.178"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "106.3.133.179"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "106.3.133.180"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "210.73.218.171"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "210.73.218.172"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[tm]]

  # ip地址
  ip = "101.251.223.190"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.178"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.179"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "106.3.133.180"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "210.73.218.171"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "210.73.218.172"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

[[bsc]]

  # ip地址
  ip = "101.251.223.190"

  # 用于确定是否为新加ip,默认为false,已弃用
  isNew = false

# bsc链server配置
[bsc-conf]

  # bsc链server token
  token = "3D3781351A3EE9E4"

# tm链server ip
[tm-conf]
  ip = "210.73.218.171"

# tm落后节点监视器
[tm-monitor]

  # 钉钉机器人接口
  ding-url = "https://oapi.dingtalk.com/robot/send?access_token=cf2758d4b768f7aa352a919c72f88e9e9fd695168147f851c38c7a78d92cbd69"

  # 钉钉安全设置,节点正常消息前缀
  ok-prefix-key = "tm节点恢复正常"

  # 钉钉安全设置,节点异常消息前缀
  err-prefix-key = "tm节点异常"

  # 获取块高时间间隔,单位为秒
  interval = 5

  # 判断区块落后所需次数
  retry-times = 5

  # 落后区块节点ip列表
  abnormal-hosts = []

# bsc节点停止出块监视
[bsc-monitor]

  # 钉钉机器人接口
  ding-url = "https://oapi.dingtalk.com/robot/send?access_token=cf2758d4b768f7aa352a919c72f88e9e9fd695168147f851c38c7a78d92cbd69"

  # 钉钉安全设置,节点正常消息前缀
  ok-prefix-key = "bsc节点恢复正常"

  # 钉钉安全设置,节点异常消息前缀
  err-prefix-key = "bsc节点异常"

  # 获取块高时间间隔,单位为秒
  interval = 10

  # 判断区块落后所需次数
  retry-times = 5

  # 落后区块节点ip列表
  abnormal-hosts = []

# 本服务配置
[service-conf]

  # 服务端口默认为6667
  port = 6667

  # 日志等级int类型默认为info; debug || info || warn || error
  log-level = "info"

  # 日志路径,默认为update.log
  log-path = "update.log"

# bsc集群监视
[bsc-cluster-monitor]

  # 查看集群状态时间间隔,默认10分钟
  cluster-interval = 600

  # bsc节点重启时间间隔,默认2分钟
  node-interval = 120

  # 用于重启bsc的rpc端口
  monitor-rpc = 8546
