
# 本服务配置
[service-conf]

  # 服务端口默认为6667
  port = 6667
  # 日志等级int类型默认为info; debug || info || warn || error
  log-level = "info"
  # 日志路径,默认为update.log
  log-path = "./tmwatch_client.log"

  # 用于触发tmclient请求的access token
  access-token = "3333"
  # 调用执行的tm脚本文件名
  invoke-script-name = "tmnode_snapdata0419KK.sh"


# 检测节点状态配置
[service-conf-monitor]
  #检测节点接口间隔时间
  request_tm_interval = 60
  #重启节点服务间隔时间
  operator_sys_interval = 30
  #节点服务启动方式
  start_mode = 0
