
# tm链server ip
[tm-conf]
  ip = "210.73.218.171"

# tm落后节点监视器
[tm-monitor]

  # 钉钉机器人接口
  ding-url = "https://oapi.dingtalk.com/robot/send?access_token=48679669f51e7aa89c4544b17bfc4c1e4a565b975d067cf3fa420b0ae0c255ef"
  #48679669f51e7aa89c4544b17bfc4c1e4a565b975d067cf3fa420b0ae0c255ef
  # 钉钉安全设置,节点正常消息前缀
  ok-prefix-key = "tm节点恢复正常"

  # 钉钉安全设置,节点异常消息前缀
  err-prefix-key = "tm节点异常"

  # 获取块高时间间隔,单位为秒
  interval = 5

  # 获取块高时间间隔,单位为秒
  ding-token = "48679669f51e7aa89c4544b17bfc4c1e4a565b975d067cf3fa420b0ae0c255ef"

# 本服务配置
[service-conf]

  # 服务端口默认为6667
  port = 6667
  # 日志等级int类型默认为info; debug || info || warn || error
  log-level = "info"
  # 日志路径,默认为update.log
  log-path = "./tmwatch_client.log"

  # 用于触发tmclient请求的access token
  access-token = "3333"
  # 调用执行的tm脚本文件名
  invoke-script-name = "tmnode_snapdata0419KK.sh"
